<a href="https://colab.research.google.com/github/DeHawk/TensorFlow/blob/master/Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
oned_array = np.array([1.2,2.4,3.5,6.7,8.9])
print(oned_array)

[1.2 2.4 3.5 6.7 8.9]


In [ ]:
twod_array = np.array([[1,2],[3,4],[5,6]])
print(twod_array)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
seq_num = np.arange(2,10,2)

print(seq_num)

[2 4 6 8]


In [ ]:
rand_int = np.random.randint(50,81,size=8)
print(rand_int)

[75 50 64 75 69 78 77 56]


In [ ]:
rand_flot = np.random.random(8)

print(rand_flot)

[0.836653   0.2803285  0.90478938 0.323944   0.61763211 0.14613129
 0.79062131 0.15325955]


In [ ]:
# broadcasting = rand floats between 4 and 5

rand_flot_4n5 = rand_flot + 4
print(rand_flot_4n5)

[4.836653   4.2803285  4.90478938 4.323944   4.61763211 4.14613129
 4.79062131 4.15325955]


In [ ]:
# create linear dataset

feature = np.arange(6,21)
label = feature*3 + 4

In [ ]:
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [ ]:
#noise1 = np.random.randint(-2,3,size=15) * np.random.random()

noise = np.random.random(15)*4 - 2

print(noise)

[ 1.87514277 -1.84787181  1.61181208  0.98841429  0.1282045   0.45396688
 -0.7738368   0.61469346  0.4847922   0.51183083  0.62451791  1.72258314
  1.85049893 -0.05308871 -1.81418782]


In [ ]:
label = label + noise

print(label)

[25.75028554 21.30425638 31.22362416 32.97682858 34.25640901 37.90793376
 38.4523264  44.22938692 46.96958441 50.02366165 53.24903582 58.44516628
 61.70099787 60.89382257 60.37162436]


In [ ]:
import pandas as pd


In [ ]:
# you need values and column names to create dataframe

my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

my_columns = ['temp','activity']

my_dataframe = pd.DataFrame(data = my_data, columns=my_columns)

print(my_dataframe)

   temp  activity
0     0         3
1    10         7
2    20         9
3    30        14
4    40        15


In [ ]:
 # add columns

 my_dataframe['adjusted'] = my_dataframe['activity'] + 3

 print(my_dataframe)

   temp  activity  adjusted
0     0         3         6
1    10         7        10
2    20         9        12
3    30        14        17
4    40        15        18


In [ ]:
# first 3 rows
print(my_dataframe.head(3))

   temp  activity  adjusted
0     0         3         6
1    10         7        10
2    20         9        12


In [ ]:
# only 3rd row
print(my_dataframe.iloc[[2]], '\n')

   temp  activity  adjusted
2    20         9        12 



In [ ]:
# slicing 3 rows

print(my_dataframe[1:4])

   temp  activity  adjusted
1    10         7        10
2    20         9        12
3    30        14        17


In [ ]:
# only column
print(my_dataframe['temp'])

0     0
1    10
2    20
3    30
4    40
Name: temp, dtype: int64


In [ ]:
my_cols = ['Elenor', 'Chidi', 'Tahani', 'Jason']
my_vals = np.random.randint(0,101, size=(3,4))

my_df = pd.DataFrame(data = my_vals, columns=my_cols)

my_df['Janet'] = my_df['Tahani'] + my_df['Jason']

print(my_df)

   Elenor  Chidi  Tahani  Jason  Janet
0      38     25      96     39    135
1      96     38      84    100    184
2      33     70      49     14     63
